((LANGUAGE . "en") (TERRITORY . "BE")
 (CALENDARS
  (GREGORIAN
   (DATE-FORMATS (SHORT (PATTERN . "dd/MM/yy"))
    (MEDIUM (PATTERN . "dd MMM y"))))
  (GENERIC (DATE-FORMATS (MEDIUM (PATTERN . "dd MMM y G"))))))
