((LANGUAGE . "en") (TERRITORY . "NZ")
 (CALENDARS
  (GREGORIAN
   (DATE-FORMATS (SHORT (PATTERN . "dd/MM/y")) (MEDIUM (PATTERN . "d MMM y"))))
  (GENERIC
   (DATE-FORMATS (SHORT (PATTERN . "d/MM/y GGGGG"))
    (MEDIUM (PATTERN . "d/MM/y G"))))))
